name: sirotodo
description: A simple Todo App created with Parse as the backend

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.1
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.8
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/
